USERMODULES_DIR := $(USERMOD_DIR)

# Add all C files to SRC_USERMOD.
SRC_USERMOD += $(USERMODULES_DIR)/compat.py.c $(USERMODULES_DIR)/externApp.c $(USERMODULES_DIR)/gateway.c

CFLAGS_USERMOD += -I$(USERMODULES_DIR) -DMODULE_GATEWAY_ENABLED=1
